server:
  port: 8899
spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300 #多个用逗号分隔
      repositories:
        enabled: true
  application:
    name: springboot-elasticsearch